services:
  vote:
    build: ./vote
    ports:
      - "5000:80"
    volumes:
      - ./vote:/app
    networks:
      - backend
      - frontend
  result:
    build: ./result
    command: nodemon server.js
    volumes:
      - ./result:/app
    ports:
      - "5001:80"
    networks:
      - backend
      - frontend
  worker:
    depends_on:
      - db
    build: ./worker
    networks:
      - backend
  redis:
    image: redis:latest
    networks:
      - backend
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'my_database'
    volumes:
    - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
  frontend:

